stages:
  - test

on-pull-requests:
  stage: test
  script: echo 'this should run on pull requests'
  only:
    - external_pull_requests

include:
  - project: "kzap/gitlab-external-pr-bug-private"
    ref: master
    file: ci-job.yaml
